---
abstract: 'A POE component for the Github API'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  HTTP::Response: 0
  POE::Filter::HTTP::Parser: 0.08
  Test::More: 0.47
  Test::POE::Server::TCP: 1.04
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.88'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-Github
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  Algorithm::FloodControl: 0
  Class::MOP: 0.84
  HTTP::Request::Common: 0
  JSON::Any: 1.19
  JSON::XS: 2.232
  Module::Pluggable: 3.9
  Moose: 0.79
  MooseX::POE: 0.202
  POE: 1.005
  POE::Component::Client::HTTP: 0.88
  POE::Component::SSLify: 0.15
  perl: 5.6.0
resources:
  homepage: http://github.com/bingos/poe-component-github/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bingos/poe-component-github.git
version: 0.04
